### ISSUE TITLE
Skip add button hover - Browser Freeze

### ISSUE THREAD

**Issue by yusufarslan** [PetroFrolov/vast-video-js#12]
If the skip button is on hover state at the end of the ad video, the browser crashes while trying to load the main video file. (Chrome - OSX 10.8.2)

**Comment by PetroFrolov** [comment]
Excuse me, I coundn't fix this bug in nearest future because I have no Apple Computers...

**Comment by shdwshard** [comment]
I'll test this configuration and write a patch if that's alright. I have concerns about this edge case for my web site.

**Comment by PetroFrolov** [comment]
I have no objections )
