### ISSUE TITLE
Autoplay - OSX

### ISSUE THREAD

**Issue by yusufarslan** [PetroFrolov/vast-video-js#13]
In Chrome and Safari Pre-roll video is played even when auto play is false on OSX (10.8.2). On Windows (Chrome) everything seems normal and the preroll is played when start is clicked.

**Comment by PetroFrolov** [comment]
I have no Apple computers but I'll check this bug in Safari on Windows...

**Comment by yusufarslan** [comment]
Hi Petro,

Maybe we can work together on this project.

**Comment by PetroFrolov** [comment]
I've added you to Skype

**Comment by cefek** [comment]
Gentlemen -

I can confirm. On OSX whole video automatically plays when you have VAST configured with pre-roll. Can't check on Windows. Have you got any suggestions?

Other than that, everything seems really EXCELLENT.

**Comment by PetroFrolov** [comment]
Hi, have no Apple comuter yet. So I couldn't check this bug. I've checked it on Ipad an all was ok.

**Comment by cefek** [comment]
Hi

Thank you for your reply. Is it possible to contact you directly via 
e-mail, regarding help/support (a little) and donation possibility?

**Comment by PetroFrolov** [comment]
I've added my email to my profile.

**Comment by cefek** [comment]
I just sent you an e-mail. Need your help I guess.

## 

Michał Nazarewicz
Redaktor Naczelny
tatapad.pl - pierwszy polski portal dla ojców
mobile +48.602403332

W dniu 28.12.2012 14:45, petro.frolov napisał(a):
