### ISSUE TITLE
Ads not playing

### ISSUE THREAD

**Issue by ajoythomas** [PetroFrolov/vast-video-js#15]
Hi, Thanks for the plugin. For some reason the ads don't play for me. I'm on a Mac and tried it on Chrome v.25, Firefox v.19, and Safari v.6. I simply downloaded the zipped file and opened the index.html file under the example folder, the main video plays but there is no preroll, mid-roll or postroll. I didn't make any edits to the plugin option. Let me know what I might be missing. Thanks!
- a

**Comment by PetroFrolov** [comment]
Hi! You must use web-server like Apache, Nginx, LIghtHttpd ...

**Comment by ajoythomas** [comment]
ah ok! works great once I ran it via apache. thanks.
