### ISSUE TITLE
Video JS 4

### ISSUE THREAD

**Issue by kefniark** [PetroFrolov/vast-video-js#20]
Some times ago, Video JS has updated their video player.
Now it's recommanded to use this one (version 4.0) :
    &lt;link href="http://vjs.zencdn.net/4.0/video-js.css" rel="stylesheet"&gt;
    &lt;script src="http://vjs.zencdn.net/4.0/video.js"></script>

in place of the old one (version 3.2.0) :
    &lt;link href="http://vjs.zencdn.net/c/video-js.css" rel="stylesheet"&gt;
    &lt;script src="http://vjs.zencdn.net/c/video.js"&gt;&lt;/script&gt;

This vast plugin works really well with the old version.
But with the new version, the plugin doesn't seems to be correctly initialized : 
"Uncaught TypeError: Cannot set property 'xdr' of undefined"

Are you planning to update this plugin to support the new Video JS ?

**Comment by bluestarforever** [comment]
I actually see this error, too. I was going crazy trying to figure it out. LOL. I thought I was making a mistake somewhere else.

**Comment by PetroFrolov** [comment]
Hi! New version of VideoJS has a bug that dosn't allow to work of my plugin correctly. I've posted a it into bugtracker, but it'is hasn't solved yet.

P.S. In v4 VideoJs has a different version of plugins API.

**Comment by E-P1983** [comment]
Did you have any chance to fix it yet?

**Comment by doublex** [comment]
Would be great, if this would work with video-js 4.

**Comment by PetroFrolov** [comment]
I've added new branch that supports v4 and back compatible with v3.
There is no new features. All code was rewrited for new arch of Video.JS.

**Comment by doublex** [comment]
Thanks a lot!
Great extension!

**Comment by E-P1983** [comment]
Awesome!!

**Comment by PetroFrolov** [comment]
Please notify me if that version not works

**Comment by E-P1983** [comment]
I will test it tonight and let it know :)

**Comment by npofopr** [comment]
v4.4 don't work? Or just me?

**Comment by sebastianlueke** [comment]
@doublex Example didn't show up any ads for me, too. System OS X Maverick Safari and FF latest Versions. Anybody has a working example with v4.4.3 of video.js?
