### ISSUE TITLE
Overlays and companion ads

### ISSUE THREAD

**Issue by cycleos** [PetroFrolov/vast-video-js#33]
Is there any chance that the plugin will read companion ads and also serve overlays within the player?

Regards

**Comment by PetroFrolov** [comment]
Hi! No .. this case is unsupported

**Comment by cubotar** [comment]
@cycleos check this plugin : https://github.com/funnyordie/videojs-imageOverlay

**Comment by cycleos** [comment]
@cubotar it doesn't support VAST. Thank you anyway.
