### ISSUE TITLE
browser issue

### ISSUE THREAD

**Issue by tania0339** [PetroFrolov/vast-video-js#6]
I've copied your example files to http://www.funnynews.it/vastvideojs/examples/index.html . I've changed all  paths in code to absolute paths, but testing it with different browsers it seems to work fine just in Chrome (not ie9, not FF, not Safari) Was I supposed to change some other path or do something else during the files setup on server?
Thanks for your work! :)

**Comment by PetroFrolov** [comment]
Hello!
I miss your message. Did you solve your problem? I've fixed the <VIDEO> tag.

**Comment by tania0339** [comment]
I ended up using flowplayer. Thanks, anyway! :)
