### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by iphony** [PetroFrolov/vast-video-js#7]
Hi,
I tried to use the VAST example as mid or pre roll without success, no advertising spot there.
Only the content without the ad is shown.
E.g. on an iPad with iOS 5.
The safari console does not show an error, so i wonder what's wrong there?
Any idea or tip?
Thanks

**Comment by PetroFrolov** [comment]
Hi,
could you send me an url of your example page?

**Comment by iphony** [comment]
Hi,
even with the example.php in your github repo, it's not inserting the pepsi spot on the ipad.

**Comment by PetroFrolov** [comment]
Ok, I'll try to solve the problem

**Comment by PetroFrolov** [comment]
solved
f027a418d316deb861d2eec73206fe1a3dd58967
