### ISSUE TITLE
VAST and VPAID version

### ISSUE THREAD

**Issue by aragorne** [PetroFrolov/vast-video-js#8]
Hello,

I think it's the wrong  place for this but I don't find how can I write a message.

What is the version off vast ? 2.0 or 3.0 

and for VPAID ? 

You make a good JOB.

Thank you.

**Comment by PetroFrolov** [comment]
Hello!
I've used VAST 2.0. There is no full standard support. Only most often used things.
And I haven't used VPAID because all player functions are on the video.js-player side.
